---
title: "Simple Probability"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE, warning=FALSE)
```



Lets load the required libraries to plot the graphs nicely

```{r}

library(ggplot2)
library(gridExtra)

```


## Can you think of similar procedure for toss a Dice.

In here instead of two outcomes we have 6 outcomes.



## toss Dice function

To demonstrate that we can create **tossDice** function & **plotDice** function similar to toss Coin.

```{r}
tossDice <- function(numToss = 10){
  dice <- c(1:6)
  result <- sample(dice, numToss, replace = TRUE)
  df_total <- data.frame(table(result))
  
}

plotDice <- function(df){
  number <- sum(df$Freq)
  
 
  plot1 <- ggplot(df, aes(result,Freq, fill = result)) + geom_bar(stat = "identity") + labs(title = paste0("Tossing a dice ", number," times")) +theme(legend.position = "none")


  plot2 <- ggplot(df, aes(result, prop.table(df$Freq), fill = result)) + geom_bar(stat = "identity") + labs(title = paste0("Probability of Tossing a dice ", number," times"), y = "Probability") + theme(legend.position = "none")
  
  grid.arrange(plot1, plot2)
}

```


Lets see the results by tossing coin 50 times

```{r}
df50 <- tossDice(50)
df50
plotDice(df50)

```

May be 1000 times


```{r}
df1000 <- tossDice(1000)
df1000
plotDice(df1000)


```
